apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      initContainers:
        - name: wait-rabbitmq
          image: redis:7-alpine
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "until nc -z rabbitmq 5672; do sleep 1; done"]
      containers:
        - name: payment-service
          image: eventhub-main-payment-service:latest
          imagePullPolicy: Never
          command: ["python", "main.py"]
          ports:
            - containerPort: 9100
              name: health
          envFrom:
            - configMapRef:
                name: eventhub-config
          env:
            - name: HEALTH_PORT
              value: "9100"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9100
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 3
